/**
 * Main - Tasks 3 and 4
 *
 * Entry point of the Corporate Talent Hub system.
 * Demonstrates operator precedence, boolean logic,
 * null handling, and object reference comparison.*/

public class Main {

    // TASK 3 - SALARY CALCULATION

    static double calculateFinalSalary(double baseSalary, double monthlyBonus) {
        return (baseSalary + (monthlyBonus * 1.10)) - (baseSalary * 0.05);
    }

    static boolean validateEligibility(int testScore, int age, int headquarterId, boolean isActive) {
        return (testScore > 85 && age < 30) || (headquarterId == 1 && !isActive);
    }

    // MAIN METHOD

    public static void main(String[] args) {

        // --- Text Block (Java 17+) ---
        // Multi-line string without escape characters like \n
        // The """ marks the start and end of the block
        String header = """
                ╔══════════════════════════════════╗
                ║     CORPORATE TALENT HUB         ║
                ║     HR Management System         ║
                ╚══════════════════════════════════╝
                """;
        System.out.println(header);

        // TASK 4 - INSTANTIATE OBJECTS

        // Creating an Employee object with all 8 primitive types
        // Note the suffixes: L for long, f for float
        Employee employee1 = new Employee(
                (byte) 3,
                (short) 2019,
                1001,
                1234567890L,
                92.5f,
                3500000.00,
                'M',
                true,
                "Carlos Ramirez",
                500000.00
        );

        // Creating a CompanyRecord — modern immutable data structure
        CompanyRecord company = new CompanyRecord(
                "Talent Corp S.A.S",
                "900-123-456-7",
                2005
        );

        // Printing company info — toString() is auto-generated by Record
        System.out.println("Company: " + company);

        // TASK 3 - APPLYING BUSINESS LOGIC

        // Compound assignment: updates monthlyBonus by adding 10% of itself
        // Same as: employee1.monthlyBonus = employee1.monthlyBonus + (employee1.monthlyBonus * 0.10)
        employee1.monthlyBonus += employee1.monthlyBonus * 0.10;
        System.out.println("Updated bonus: " + employee1.monthlyBonus);

        // Calculate final salary using operator precedence
        double finalSalary = calculateFinalSalary(employee1.baseSalary, employee1.monthlyBonus);
        System.out.println("Final salary: " + finalSalary);

        // Extra bonus if employee ID is even (modulo operator)
        if (employee1.employeeId % 2 == 0) {
            System.out.println("Employee qualifies for extra bonus (even ID)");
        } else {
            System.out.println("Employee does not qualify for extra bonus (odd ID)");
        }

        // Validate eligibility using complex boolean logic
        boolean isEligible = validateEligibility(95, 27, 1, employee1.isActive);
        System.out.println("Employee is eligible: " + isEligible);

        // TASK 4 - NULL LABORATORY

        // Assigning null to a String attribute
        // null means the variable exists but points to nothing in the Heap
        employee1.fullName = null;

        // HELPFUL NULLPOINTEREXCEPTION (Java 14+):
        // If we try to call a method on null, Java throws a NullPointerException.
        // Java 14+ tells you EXACTLY which variable was null:
        //   "Cannot invoke String.length() because employee1.fullName is null"
        // Java 8 only said: "NullPointerException" — no details, hard to debug.
        //
        // Uncomment the line below to see it in action:
        // System.out.println(employee1.fullName.length());

        System.out.println("Full name value: " + employee1.fullName); // prints null safely

        // TASK 4 - OBJECT REFERENCE COMPARISON

        Employee employee2 = new Employee(
                (byte) 3,
                (short) 2019,
                1001,
                1234567890L,
                92.5f,
                3500000.00,
                'T',
                true,
                "Carlos Ramirez",
                500000.00
        );

        // == compares REFERENCES, not values
        // employee1 and employee2 are two different objects in the Heap
        // even if they have identical data, they live in different memory addresses
        // so == returns false
        System.out.println("employee1 == employee2: " + (employee1 == employee2));

        // To compare values, you would use .equals() — but Employee doesn't
        // override it yet, so that's a topic for later.
    }
}